version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend-ui"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/backend-api"
    schedule:
      interval: "weekly"
