name: Frontend UI Angular Build Status

on:
  push:
    branches:
    - main
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-ui
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Run tests
      run: npm run test

    - name: Build
      run: npm run build

    - name: Deploy
      if: success()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: frontend-ui/dist
        branch: gh-pages